services:
  app:
    build: .
    container_name: node-alexa-skill:latest
    ports:
      - "4040:4040"
    environment:
      - NODE_ENV=production
    volumes:
      - /logs:/app/logs

  ngrok:
    image: ngrok/ngrok:latest
    container_name: ngrok
    depends_on:
      - app
    command: >
      http app:4040
    environment:
      - NGROK_AUTHTOKEN=${NGROK_AUTHTOKEN}